# Tasky -- developer entry points.  `make help` lists them.
.DEFAULT_GOAL := help
SHELL := /usr/bin/env bash

COMPOSE := docker compose
BACKEND := backend
FRONTEND := frontend

.PHONY: help
help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-14s\033[0m %s\n",$$1,$$2}'

.env:
	cp .env.example .env

# ---------------------------------------------------------------- stack
.PHONY: up down logs ps
up: .env ## Build and start db, mailpit, api, worker, web
	GIT_SHA=$$(git rev-parse --short HEAD 2>/dev/null || echo dev) $(COMPOSE) up -d --build
	bash scripts/wait-for-health.sh
	@echo "web http://localhost:5173 | api http://localhost:8000/docs | mail http://localhost:8025"

down: ## Stop the stack (keeps the database volume)
	$(COMPOSE) down

logs: ## Follow api + worker logs
	$(COMPOSE) logs -f api worker

ps: ## Show container status
	$(COMPOSE) ps

# ---------------------------------------------------------------- setup
.PHONY: install
install: ## Install backend (venv) and frontend dependencies for local work
	cd $(BACKEND) && python3.12 -m venv .venv && $(VENV_BIN)/pip install -e '.[dev]'
	cd $(FRONTEND) && npm ci

# ---------------------------------------------------------------- quality
.PHONY: lint format test test-fast test-backend test-frontend
lint: ## Ruff + mypy + ESLint + tsc + Prettier check
	cd $(BACKEND) && ruff check . && ruff format --check . && mypy app
	cd $(FRONTEND) && npm run lint && npm run typecheck && npm run format:check

format: ## Auto-format backend and frontend
	cd $(BACKEND) && ruff check --fix . && ruff format .
	cd $(FRONTEND) && npm run format

test: test-backend test-frontend ## Run every test suite

test-backend: ## pytest with coverage (needs Postgres: `make up` or DATABASE_URL)
	cd $(BACKEND) && pytest --cov=app --cov-report=term-missing

test-fast: ## pytest without slow tests
	cd $(BACKEND) && pytest -m "not slow" -q

.PHONY: eval e2e
eval: ## Triage accuracy on the 20 labelled incidents (rule engine; add ENGINE=llm for the model)
	cd $(BACKEND) && $(VENV_BIN)/python -m evals.triage_eval --engine $(or $(ENGINE),rules)

e2e: ## Playwright smoke flow against the running dev stack (API with a raised login limit)
	cd $(FRONTEND) && npx playwright test

test-frontend: ## Vitest (single run)
	cd $(FRONTEND) && npm test -- --run

# ---------------------------------------------------------------- local dev without Docker
# Windows needs the selector loop for async psycopg (Linux/Docker is unaffected).
UVICORN_LOOP := $(if $(filter Windows_NT,$(OS)),--loop asyncio:SelectorEventLoop,)
VENV_BIN := $(if $(filter Windows_NT,$(OS)),.venv/Scripts,.venv/bin)

.PHONY: dev-api dev-worker dev-web gen-client
dev-api: ## Run the API on :8000 against DATABASE_URL (applies migrations first)
	cd $(BACKEND) && $(VENV_BIN)/alembic upgrade head && $(VENV_BIN)/uvicorn app.main:app --port 8000 $(UVICORN_LOOP)

dev-worker: ## Run the notification worker
	cd $(BACKEND) && $(VENV_BIN)/python -m app.notifications.worker

dev-web: ## Run the Vite dev server (proxies /api to :8000)
	cd $(FRONTEND) && npm run dev

gen-client: ## Regenerate frontend/openapi.json and the TypeScript API types
	cd $(BACKEND) && $(VENV_BIN)/python -m app.scripts.export_openapi ../frontend/openapi.json
	cd $(FRONTEND) && npm run gen:api

# ---------------------------------------------------------------- database
.PHONY: migrate migration db-shell seed seed-local seed-reset check
migrate: ## Apply migrations inside the api container
	$(COMPOSE) exec api alembic upgrade head

migration: ## New autogenerated migration:  make migration m="add users"
	@test -n "$(m)" || (echo 'usage: make migration m="message"' && exit 1)
	$(COMPOSE) exec api alembic revision --autogenerate -m "$(m)"

seed: ## Demo users + 25 incidents inside the api container
	$(COMPOSE) exec api python -m app.scripts.seed

seed-local: ## Demo users + 25 incidents against DATABASE_URL (no Docker)
	cd $(BACKEND) && $(VENV_BIN)/python -m app.scripts.seed

seed-reset: ## Wipe incidents and re-seed the demo data (no Docker)
	cd $(BACKEND) && $(VENV_BIN)/python -m app.scripts.seed --reset


check: ## Check database, email, storage and AI with the current .env (to=you@x.com sends a test email)
	cd $(BACKEND) && $(VENV_BIN)/python -m app.scripts.check_integrations $(if $(to),--send-test-email $(to),)

db-shell: ## psql into the local database
	$(COMPOSE) exec db psql -U app -d incidents
