"""attachments and ai suggestions

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-22 13:38:48.297416+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        for value in ("attachment_added", "attachment_deleted", "ai_applied"):
            op.execute(f"ALTER TYPE incident_event_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_suggestions",
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("triage", "summary", "postmortem", "nl_search", name="ai_suggestion_kind"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "rejected", name="ai_suggestion_status"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_ai_suggestions_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_suggestions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_suggestions")),
    )
    op.create_index(
        "ix_ai_suggestions_incident_created",
        "ai_suggestions",
        ["incident_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_suggestions_user_created", "ai_suggestions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("comment_id", sa.Uuid(), nullable=True),
        sa.Column("uploader_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 10485760", name=op.f("ck_attachments_size_limit")
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_attachments_comment_id_comments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_attachments_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploader_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_attachments_storage_key")),
    )
    op.create_index(
        "ix_attachments_incident_created",
        "attachments",
        ["incident_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attachments_incident_created", table_name="attachments")
    op.drop_table("attachments")
    op.drop_index("ix_ai_suggestions_user_created", table_name="ai_suggestions")
    op.drop_index("ix_ai_suggestions_incident_created", table_name="ai_suggestions")
    op.drop_table("ai_suggestions")
    op.execute("DROP TYPE IF EXISTS ai_suggestion_kind")
    op.execute("DROP TYPE IF EXISTS ai_suggestion_status")
    # ### end Alembic commands ###
    # Postgres cannot drop enum values; the three event types stay (unused) on downgrade.
