"""event sequence

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-22 10:27:25.694811+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    )
    op.create_index(
        "ix_incident_events_seq", "incident_events", [sa.literal_column("seq DESC")], unique=False
    )
    op.create_unique_constraint(op.f("uq_incident_events_seq"), "incident_events", ["seq"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_incident_events_seq"), "incident_events", type_="unique")
    op.drop_index("ix_incident_events_seq", table_name="incident_events")
    op.drop_column("incident_events", "seq")
    # ### end Alembic commands ###
