"""notifications watchers heartbeats

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-22 11:11:22.169169+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # New audit event types. ADD VALUE cannot run inside a transaction block that later
    # uses the value, so it runs in its own autocommit block.
    with op.get_context().autocommit_block():
        for value in ("watcher_added", "watcher_removed", "sla_breached"):
            op.execute(f"ALTER TYPE incident_event_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_heartbeats",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "beat_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "info", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_worker_heartbeats")),
    )
    op.create_table(
        "incident_watchers",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_watchers_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_incident_watchers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("incident_id", "user_id", name=op.f("pk_incident_watchers")),
    )
    op.create_table(
        "in_app_notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "incident_assigned",
                "incident_resolved",
                "incident_commented",
                "mentioned",
                "sla_breached",
                name="notification_kind",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.String(length=400), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_in_app_notifications_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["incident_events.id"],
            name=op.f("fk_in_app_notifications_event_id_incident_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_in_app_notifications_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_in_app_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_in_app_notifications")),
        sa.UniqueConstraint(
            "event_id", "user_id", "kind", name="uq_in_app_notifications_event_user_kind"
        ),
    )
    op.create_index(
        "ix_in_app_notifications_user_created",
        "in_app_notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_user_read",
        "in_app_notifications",
        ["user_id", "read_at"],
        unique=False,
    )
    op.create_table(
        "notification_outbox",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_email", sa.String(length=320), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "incident_assigned",
                "incident_resolved",
                "incident_commented",
                "mentioned",
                "sla_breached",
                name="notification_kind",
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="outbox_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["incident_events.id"],
            name=op.f("fk_notification_outbox_event_id_incident_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_notification_outbox_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notification_outbox_recipient_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
        sa.UniqueConstraint(
            "event_id", "recipient_user_id", "kind", name="uq_notification_outbox_event_user_kind"
        ),
    )
    op.create_index(
        "ix_notification_outbox_due",
        "notification_outbox",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_notification_outbox_recipient_created",
        "notification_outbox",
        ["recipient_user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_outbox_recipient_created", table_name="notification_outbox")
    op.drop_index(
        "ix_notification_outbox_due",
        table_name="notification_outbox",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("notification_outbox")
    op.drop_index("ix_in_app_notifications_user_read", table_name="in_app_notifications")
    op.drop_index("ix_in_app_notifications_user_created", table_name="in_app_notifications")
    op.drop_table("in_app_notifications")
    op.drop_table("incident_watchers")
    op.drop_table("worker_heartbeats")
    # ### end Alembic commands ###
    for enum_name in ("notification_kind", "outbox_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # Postgres cannot drop enum values; the extra incident_event_type values stay (unused).
